const Menu = [
  {
    id: 1,
    image: "/images/gethome1.png",
    name: "Gethome.id Apps",
    category: "Apps",
    description:
      "Gethome is a platform intended for you to live in a comfortable and suitable home according to your needs. With a digital ecosystem that connects you with every support system (contractors, foremen, suppliers, vendors, notaries, and so on), the desire to have a dream residence is in sight.",
    to: "/",
    alt: "team project",
    see: "See More",
    description_dua:
      "For mvp version 1.0.0, gethome.id apps display the progress of building a special house for those of you who bought a house on a project in gethome.id. You can see photos and the progress of the house construction which will be updated every week so you don't have to come directly to the location.",
    image_satu: "/images/gethome2.png",
    image_dua: "/images/gethome3.png",
    image_tiga: "/images/gethome4.png",
    to_playstore:
      "https://play.google.com/store/apps/details?id=id.gethome.myhome",
    to_appstore: "https://apps.apple.com/id/app/gethome-id/id1626773228",
    playstore: "/images/playstore.png",
    appstore: "/images/appstore.png",
  },
  {
    id: 2,
    image: "/images/roastkuy1.png",
    name: "Roastkuy Apps",
    category: "Apps",
    description:
      "Roastkuy is a special restaurant of the best grilled chicken with a sprinkling of marinades and a variety of appetizing sauces. enjoy the deliciousness of every bite at every outlet available in the Depok and Bogor areas.",
    to: "/",
    alt: "team project",
    see: "See More",
    description_dua: "",
    image_satu: "/images/roastkuy2.png",
    image_dua: "/images/roastkuy3.png",
    image_tiga: "/images/roastkuy4.png",
    to_playstore:
      "https://play.google.com/store/apps/details?id=id.roastkuy.apps",
    to_appstore: "",
    playstore: "/images/playstore.png",
    appstore: "",
  },
  {
    id: 3,
    image: "/images/ngaji1.png",
    name: "Ngaji Kuy",
    category: "Apps",
    description:
      "Ngaji kuy is an application for recitation with a complete collection of letters and prayers. With the help of audio and prayer time make this application easy to use by anyone.",
    to: "/",
    alt: "personal project",
    see: "See More",
    description_dua: "",
    image_satu: "/images/ngaji2.png",
    image_dua: "/images/ngaji3.png",
    image_tiga: "/images/ngaji4.png",
    to_playstore: "",
    to_appstore: "",
    playstore: "",
    appstore: "",
  },
  {
    id: 4,
    image: "/images/koop1.png",
    name: "Koperasi Digital Propertree",
    category: "Apps",
    description:
      "Koperasi as one of the driving forces of the Indonesian economy, combined with the spirit of digitalization of technology, produce the Koperasi Digital Propertree, a service koperasi that focuses on the property sector.",
    to: "/",
    alt: "team project",
    see: "See More",
    description_dua: "",
    image_satu: "/images/koop2.png",
    image_dua: "/images/koop3.png",
    image_tiga: "/images/koop4.png",
    to_playstore:
      "https://play.google.com/store/apps/details?id=id.koperasipropertree.apps",
    to_appstore:
      "https://apps.apple.com/id/app/koperasi-digital-propertree/id6445837757",
    playstore: "/images/playstore.png",
    appstore: "/images/appstore.png",
  },
  {
    id: 5,
    image: "/images/phinter2.jpg",
    name: "Phinter Mobile",
    category: "Apps",
    description:
      "Phinter Mobile is an online attendance application for employees with a work check-in and check-out feature using location calculations, and the process of applying for permits, leave and so on with just one request.",
    to: "/",
    alt: "team project",
    see: "See More",
    description_dua: "",
    image_satu: "/images/phinter1.jpg",
    image_dua: "/images/phinter3.jpg",
    image_tiga: "/images/phinter4.jpg",
    to_playstore: "",
    to_appstore: "https://apps.apple.com/us/app/phinter-mobile/id6475161724",
    playstore: "",
    appstore: "/images/appstore.png",
  },
];

export default Menu;
